### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by jerearaujo03** [Stolz/laravel-schema-spy#3]
I'm getting
`WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

**Comment by Stolz** [comment]
Hi @jerearaujo03.

That is a Java error so it means the error is being triggered by the SchemaSpy Java command, not by this Laravel package. It seems you didn't provide a valid certificate for your Mysql server. Since I can't reproduce the error the help I can offer is very limited.

I've done some research and the workaround seems to be disabling SSL in you Java database connection properties.

Since SchemaSpy has an option (`-connprops`) to provide a connection properties file, you can try to create a file with this content

    useSSL=false

And then add the `-connprops` option to your laravel `config/spy.php` file pointing to that file

    // file: config/spy.php
    'parameters' => [
        ...
        '-connprops' => '/path/to/the/connection/properties/file',
    ],
